import type { Bi } from "./types";

// UI copy. Content strings (lessons, sources) live in ../content.
export const S = {
  brandTagline: { en: "Knowledge that brings you closer", ar: "علمٌ يقرّبك" },
  motto: { en: "Learn · Reflect · Live it", ar: "علمٌ أعمق .. حياةٌ أقرب" },

  nav: {
    home: { en: "Home", ar: "الرئيسية" },
    learn: { en: "Learn", ar: "تعلّم" },
    library: { en: "Library", ar: "المكتبة" },
    quran: { en: "Quran & Translations", ar: "القرآن والترجمات" },
    quranShort: { en: "Quran", ar: "القرآن" },
    ask: { en: "Ask & Check", ar: "اسأل وتحقّق" },
    compare: { en: "Religion & Belief Comparison", ar: "مقارنة الأديان والمعتقدات" },
    compareShort: { en: "Compare", ar: "مقارنة" },
    sources: { en: "Our sources", ar: "مصادرنا" },
    educators: { en: "For educators", ar: "للمعلّمين" },
    signIn: { en: "Sign in", ar: "تسجيل الدخول" },
    getStarted: { en: "Get started", ar: "ابدأ الآن" },
    dashboard: { en: "Dashboard", ar: "لوحتي" },
    myLearning: { en: "My learning", ar: "تعلّمي" },
    instructor: { en: "Studio", ar: "الاستوديو" },
    signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  },

  hero: {
    eyebrow: { en: "Knowledge that brings you closer", ar: "علمٌ يقرّبك" },
    title1: { en: "Understand Islam,", ar: "افهم الإسلام" },
    title2: { en: "one clear step at a time", ar: "خطوةً واضحةً بعد خطوة" },
    sub: {
      en: "Short visual lessons you can listen to and talk to, in Arabic and English, with every claim traceable to an approved source.",
      ar: "دروس بصرية قصيرة تستمع إليها وتحاورها، بالعربية والإنجليزية، وكل معلومة فيها مرتبطة بمصدرها المعتمد.",
    },
    cta: { en: "Start learning free", ar: "ابدأ التعلّم مجانًا" },
    cta2: { en: "Try the tutor", ar: "جرّب المعلّم" },
  },

  pillars: {
    sources: { en: "Approved sources", ar: "مصادر معتمدة" },
    sourcesSub: { en: "Qur'an · Hadith · Scholarship", ar: "القرآن · الحديث · أهل العلم" },
    ai: { en: "Grounded AI", ar: "ذكاء اصطناعي منضبط" },
    aiSub: { en: "Answers only from sources", ar: "يجيب من المصادر فقط" },
    everyone: { en: "For every learner", ar: "لكل متعلّم" },
    everyoneSub: { en: "Curious · New · Deepening", ar: "باحث · مسلم جديد · متعمّق" },
    langs: { en: "Bilingual", ar: "ثنائي اللغة" },
    langsSub: { en: "العربية · English", ar: "العربية · English" },
  },

  journey: {
    title: { en: "Begin your journey", ar: "ابدأ رحلتك" },
    sub: {
      en: "Three paths, one scholarly reference. Pick the one that fits you today — you can switch any time.",
      ar: "ثلاثة مسارات ومرجعية علمية واحدة. اختر ما يناسبك اليوم، ويمكنك التبديل متى شئت.",
    },
    open: { en: "Open track", ar: "افتح المسار" },
  },

  trust: {
    title: { en: "Built on approved, traceable sources", ar: "مبنيّ على مصادر معتمدة يمكن تتبّعها" },
    sub: {
      en: "We follow the challenge's scholarly reference. Revealed text is shown verbatim — never generated.",
      ar: "نلتزم بالمرجعية العلمية للتحدي. يُعرض النص الشرعي بنصّه، ولا يُولَّد أبدًا.",
    },
    quran: { en: "Qur'an", ar: "القرآن الكريم" },
    quranSub: { en: "Verified Uthmani text", ar: "النص العثماني الموثّق" },
    hadith: { en: "Sahih hadith", ar: "الحديث الصحيح" },
    hadithSub: { en: "With collection and grading", ar: "مع المصدر والحكم" },
    tafsir: { en: "Tafsir", ar: "التفسير" },
    tafsirSub: { en: "Classical explanation", ar: "شروح أهل العلم" },
    review: { en: "Human review", ar: "مراجعة علمية" },
    reviewSub: { en: "Every lesson approved", ar: "كل درس معتمد" },
    levels: { en: "Four answer levels", ar: "أربعة مستويات للإجابة" },
    levelsSub: { en: "Cite · explain · note differences · refer", ar: "توثيق · شرح · بيان الخلاف · إحالة" },
  },

  features: {
    title: { en: "A clearer way to learn", ar: "طريقة أوضح للتعلّم" },
    sub: { en: "Modern tools, faithful to the sources.", ar: "أدوات حديثة، أمينة على المصادر." },
    lessons: { en: "Visual micro-lessons", ar: "دروس بصرية قصيرة" },
    lessonsSub: {
      en: "One idea per card, an illustration, a takeaway — read or listen.",
      ar: "فكرة واحدة في كل بطاقة، مع صورة وخلاصة — اقرأ أو استمع.",
    },
    tutor: { en: "Ask & Check tutor", ar: "معلّم «اسأل وتحقّق»" },
    tutorSub: {
      en: "Ask by voice or text. It cites its sources, or says it can't.",
      ar: "اسأل بالصوت أو النص. يذكر مصادره، أو يخبرك أنه لا يملك مصدرًا.",
    },
    explain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    explainSub: {
      en: "Explain an idea out loud; we show what you missed and why.",
      ar: "اشرح الفكرة بصوتك، فنبيّن لك ما فاتك ودليله.",
    },
    progress: { en: "Steady progress", ar: "تقدّم ثابت" },
    progressSub: {
      en: "Today's plan, reviews and streaks — tracking learning, never faith.",
      ar: "خطة اليوم والمراجعة والاستمرارية — نتابع التعلّم، لا الإيمان.",
    },
  },

  promise: {
    title: { en: "Our promise to learners", ar: "عهدنا مع المتعلّمين" },
    p1: { en: "No answer without a source — or an honest “I don't know”.", ar: "لا إجابة بلا مصدر — أو «لا أعلم» بصدق." },
    p2: { en: "No personal fatwa. Personal cases go to a qualified scholar.", ar: "لا فتوى شخصية. تُحال الحالات الخاصة إلى عالم مؤهّل." },
    p3: { en: "We never infer or store your beliefs.", ar: "لا نستنتج قناعاتك ولا نخزّنها." },
    p4: { en: "Every lesson is reviewed by a person before it is published.", ar: "كل درس يراجعه إنسان قبل نشره." },
  },

  footer: {
    line: { en: "One platform. A clearer path.", ar: "منصة واحدة. طريق أوضح." },
    about: { en: "About", ar: "عن يقين" },
    privacy: { en: "Privacy", ar: "الخصوصية" },
    method: { en: "Our method", ar: "منهجنا" },
    ai: {
      en: "Yaqin uses AI. Explanations are AI-assisted and reviewed; revealed text is shown verbatim from approved sources.",
      ar: "يستخدم «يقين» الذكاء الاصطناعي. الشروح مدعومة به ومراجَعة، والنص الشرعي يُعرض بنصّه من المصادر المعتمدة.",
    },
  },

  auth: {
    welcome: { en: "Welcome back", ar: "أهلًا بعودتك" },
    welcomeSub: { en: "Sign in to continue your journey with Yaqin.", ar: "سجّل الدخول لمتابعة رحلتك مع يقين." },
    create: { en: "Create your account", ar: "أنشئ حسابك" },
    createSub: { en: "Save your progress across devices.", ar: "احفظ تقدّمك على كل أجهزتك." },
    email: { en: "Email address", ar: "البريد الإلكتروني" },
    password: { en: "Password", ar: "كلمة المرور" },
    name: { en: "Your name", ar: "اسمك" },
    remember: { en: "Remember me", ar: "تذكّرني" },
    forgot: { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
    signIn: { en: "Sign in", ar: "تسجيل الدخول" },
    signUp: { en: "Create account", ar: "إنشاء الحساب" },
    or: { en: "or", ar: "أو" },
    google: { en: "Continue with Google", ar: "المتابعة عبر Google" },
    guest: { en: "Continue as guest", ar: "المتابعة كزائر" },
    guestSub: { en: "Explore lessons without an account", ar: "استكشف الدروس دون حساب" },
    noAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
    haveAccount: { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
    checkEmail: { en: "Check your email to confirm your account.", ar: "تحقّق من بريدك لتأكيد الحساب." },
    resetSent: { en: "If that email exists, a reset link is on its way.", ar: "إن كان البريد مسجّلًا فسيصلك رابط إعادة التعيين." },
    unavailable: {
      en: "Accounts are not configured on this deployment yet — continue as a guest.",
      ar: "الحسابات غير مفعّلة في هذه النسخة بعد — تابع كزائر.",
    },
    sideTitle1: { en: "Deeper learning,", ar: "تعلّمٌ أعمق" },
    sideTitle2: { en: "a brighter tomorrow", ar: "وغدٌ أنقى" },
    sideSub: {
      en: "Learn with approved Islamic sources, guided by grounded AI, for a more conscious and confident you.",
      ar: "تعلّم من مصادر إسلامية معتمدة، بإرشاد ذكاء اصطناعي منضبط، لتزداد وعيًا وثقة.",
    },
  },

  onboarding: {
    step: { en: "Step", ar: "الخطوة" },
    of: { en: "of", ar: "من" },
    trackQ: { en: "Where would you like to start?", ar: "من أين تحبّ أن تبدأ؟" },
    trackHint: {
      en: "This only chooses your lessons. We don't record anything about your beliefs.",
      ar: "هذا يحدّد دروسك فقط. لا نسجّل شيئًا عن قناعاتك.",
    },
    langQ: { en: "Which language do you prefer?", ar: "ما اللغة التي تفضّلها؟" },
    timeQ: { en: "How much time per day?", ar: "كم من الوقت يوميًا؟" },
    minutes: { en: "min / day", ar: "دقيقة يوميًا" },
    checkQ: { en: "A quick check, to find your starting point", ar: "اختبار سريع لتحديد نقطة البداية" },
    checkHint: { en: "It's fine to skip or guess.", ar: "لا بأس أن تتخطّى أو تخمّن." },
    skip: { en: "Skip", ar: "تخطَّ" },
    next: { en: "Next", ar: "التالي" },
    back: { en: "Back", ar: "رجوع" },
    finish: { en: "Show my plan", ar: "اعرض خطتي" },
  },

  dash: {
    // Greeting per track: "explore" learners may not be Muslim, so no religious salutation.
    greeting: {
      explore: {
        hello: { en: "Welcome", ar: "أهلًا بك" },
        sub: { en: "Explore Islam at your own pace, with clear answers from trusted sources.", ar: "اكتشف الإسلام على مهلك، بإجابات واضحة من مصادر موثوقة." },
      },
      "first-steps": {
        hello: { en: "Assalamu alaikum", ar: "السلام عليكم" },
        sub: { en: "Welcome to your first steps. One small, clear step at a time.", ar: "مرحبًا بك في خطواتك الأولى. خطوة صغيرة واضحة كل مرة." },
      },
      deepen: {
        hello: { en: "Assalamu alaikum", ar: "السلام عليكم" },
        sub: { en: "May your pursuit of knowledge be a means of barakah.", ar: "جعل الله طلبك للعلم سببًا للبركة." },
      },
    },
    yourTrack: { en: "Your track", ar: "مسارك" },
    today: { en: "Today's plan", ar: "خطة اليوم" },
    completed: { en: "completed", ar: "مكتمل" },
    journey: { en: "Your learning journey", ar: "رحلتك التعليمية" },
    level: { en: "Level", ar: "المستوى" },
    comingSoon: { en: "Coming soon", ar: "قريبًا" },
    locked: { en: "Finish the previous level to unlock", ar: "أكمل المستوى السابق لفتحه" },
    prevLevel: { en: "Previous level", ar: "المستوى السابق" },
    nextLevel: { en: "Next level", ar: "المستوى التالي" },
    road: {
      done: { en: "Completed", ar: "مكتمل" },
      now: { en: "In progress", ar: "قيد التعلّم" },
      planned: { en: "Planned", ar: "مخطّط" },
    },
    streak: { en: "Day streak", ar: "أيام متتالية" },
    streakHint: {
      en: "The number of days in a row you've learned.",
      ar: "عدد الأيام المتتالية التي تعلّمت فيها.",
    },
    lessonsDone: { en: "Lessons completed", ar: "دروس مكتملة" },
    continue: { en: "Continue", ar: "تابع" },
    start: { en: "Start", ar: "ابدأ" },
    review: { en: "Review", ar: "راجع" },
    guestNote: {
      en: "You're learning as a guest. Progress is saved on this device only.",
      ar: "أنت تتعلّم كزائر. يُحفظ تقدّمك على هذا الجهاز فقط.",
    },
    saveProgress: { en: "Create an account to save it", ar: "أنشئ حسابًا لحفظه" },
    stages: {
      foundations: { en: "Foundations", ar: "الأساس" },
      understanding: { en: "Understanding", ar: "الفهم" },
      practice: { en: "Practice", ar: "التطبيق" },
      impact: { en: "Living it", ar: "العمل به" },
    },
    planRead: { en: "Read", ar: "اقرأ" },
    planExplain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    planQuiz: { en: "Quick check", ar: "اختبار قصير" },
    planAsk: { en: "Ask one question you've wondered about", ar: "اسأل سؤالًا شغلك" },
  },

  library: {
    title: { en: "Lessons library", ar: "مكتبة الدروس" },
    sub: { en: "Explore. Discover. Learn what matters.", ar: "استكشف، واكتشف، وتعلّم ما يهمّك." },
    search: { en: "Search lessons or topics…", ar: "ابحث في الدروس أو الموضوعات…" },
    all: { en: "All tracks", ar: "كل المسارات" },
    filter: { en: "Filter by track", ar: "تصفية حسب المسار" },
    views: { en: "Library views", ar: "طرق عرض المكتبة" },
    learnTab: { en: "Learn Islam", ar: "تعلّم الإسلام" },
    browseTab: { en: "Browse lessons", ar: "تصفّح الدروس" },
    learnTitle: { en: "Start exploring Islam.", ar: "ابدأ اكتشاف الإسلام." },
    learnSub: { en: "Learn the basics, one step at a time.", ar: "تعلّم الأساسيات، خطوة بخطوة." },
    startLearning: { en: "Start learning", ar: "ابدأ التعلّم" },
    continueLearning: { en: "Continue learning", ar: "تابع التعلّم" },
    allDone: { en: "You have completed every available lesson.", ar: "أكملت جميع الدروس المتاحة." },
    notStarted: { en: "Not started", ar: "لم يبدأ بعد" },
    recommended: { en: "Recommended next", ar: "الدرس التالي المقترح" },
    askHint: { en: "Have a question about what you read?", ar: "هل لديك سؤال عمّا قرأت؟" },
    lessons: { en: "lessons", ar: "دروس" },
    cards: { en: "cards", ar: "بطاقات" },
    min: { en: "min", ar: "د" },
    foundation: { en: "Foundation", ar: "تمهيدي" },
    deeper: { en: "Deeper", ar: "متعمّق" },
    levels: {
      1: { en: "Level 1", ar: "المستوى ١" },
      2: { en: "Level 2", ar: "المستوى ٢" },
      3: { en: "Level 3", ar: "المستوى ٣" },
      4: { en: "Level 4", ar: "المستوى ٤" },
    },
    empty: { en: "No lessons match that search yet.", ar: "لا توجد دروس مطابقة بعد." },
  },

  lesson: {
    back: { en: "Back to library", ar: "العودة إلى المكتبة" },
    of: { en: "of", ar: "من" },
    listen: { en: "Listen", ar: "استمع" },
    pause: { en: "Pause", ar: "إيقاف" },
    sources: { en: "Sources", ar: "المصادر" },
    ask: { en: "Ask the tutor", ar: "اسأل المعلّم" },
    continue: { en: "Continue", ar: "متابعة" },
    previous: { en: "Previous", ar: "السابق" },
    revealed: { en: "Revealed text", ar: "نص شرعي" },
    generated: { en: "AI-assisted explanation · reviewed", ar: "شرح مدعوم بالذكاء الاصطناعي · مُراجَع" },
    pendingReview: { en: "Source pending scholarly review", ar: "المصدر بانتظار المراجعة العلمية" },
    obligatory: { en: "Obligatory", ar: "واجب" },
    recommended: { en: "Recommended", ar: "مستحب" },
    suggestion: { en: "Learning suggestion", ar: "اقتراح تعلّم" },
    explainTitle: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    explainHint: {
      en: "Say it out loud or type it. There's no grade — this just shows what to review.",
      ar: "قلها بصوتك أو اكتبها. لا درجات هنا — نبيّن لك فقط ما تراجعه.",
    },
    record: { en: "Record", ar: "سجّل" },
    stop: { en: "Stop", ar: "أوقف" },
    typeInstead: { en: "…or type your explanation", ar: "…أو اكتب شرحك" },
    check: { en: "Check my explanation", ar: "تحقّق من شرحي" },
    good: { en: "You covered", ar: "أحسنت في" },
    missed: { en: "You missed", ar: "فاتك" },
    tryAgain: { en: "Try again", ar: "حاول مرة أخرى" },
    simpler: { en: "Explain more simply", ar: "اشرح بأبسط" },
    quizTitle: { en: "Quick check", ar: "اختبار قصير" },
    correct: { en: "Correct", ar: "صحيح" },
    notQuite: { en: "Not quite", ar: "ليس تمامًا" },
    doneTitle: { en: "Lesson complete", ar: "اكتمل الدرس" },
    doneSub: { en: "Well done. Here's what's next.", ar: "أحسنت. إليك الخطوة التالية." },
    nextLesson: { en: "Next lesson", ar: "الدرس التالي" },
    toDashboard: { en: "Back to my plan", ar: "العودة إلى خطتي" },
    companion: { en: "AI companion", ar: "الرفيق الذكي" },
    companionSub: { en: "Ask about this lesson", ar: "اسأل عن هذا الدرس" },
    companionPlaceholder: { en: "What would you like to understand better?", ar: "ما الذي تودّ فهمه أكثر؟" },
    notes: { en: "My notes", ar: "ملاحظاتي" },
    notesPlaceholder: { en: "Write a note…", ar: "اكتب ملاحظة…" },
    progress: { en: "Lesson progress", ar: "تقدّم الدرس" },
    stepCards: { en: "Read the cards", ar: "اقرأ البطاقات" },
    stepExplain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    stepQuiz: { en: "Answer the quick check", ar: "أجب عن الاختبار" },
    stepDone: { en: "Mark as complete", ar: "أكمل الدرس" },
    voiceUnsupported: {
      en: "Voice input isn't supported in this browser — please type instead.",
      ar: "الإدخال الصوتي غير مدعوم في هذا المتصفح — اكتب بدلًا من ذلك.",
    },
    notFound: { en: "We couldn't find that lesson.", ar: "لم نجد هذا الدرس." },
  },

  ask: {
    title: { en: "Ask & Check", ar: "اسأل وتحقّق" },
    sub: { en: "Get answers you can trust. Always grounded in approved sources.", ar: "إجابات تثق بها، مستندة دائمًا إلى مصادر معتمدة." },
    placeholder: { en: "Ask a question…", ar: "اكتب سؤالك…" },
    send: { en: "Send", ar: "أرسل" },
    newChat: { en: "New chat", ar: "محادثة جديدة" },
    examples: { en: "Example questions", ar: "أسئلة مقترحة" },
    trusted: { en: "Approved sources", ar: "المصادر المعتمدة" },
    related: { en: "Sources in this answer", ar: "مصادر هذه الإجابة" },
    thinking: { en: "Checking the sources…", ar: "نراجع المصادر…" },
    disclaimer: {
      en: "AI-generated. It answers only from approved sources and can still make mistakes — for personal rulings, ask a qualified scholar.",
      ar: "إجابة مولَّدة بالذكاء الاصطناعي. تستند إلى المصادر المعتمدة فقط وقد تخطئ — وللأحكام الشخصية اسأل عالمًا مؤهّلًا.",
    },
    error: {
      en: "The tutor is unavailable right now. Please try again in a moment.",
      ar: "المعلّم غير متاح الآن. حاول مجددًا بعد قليل.",
    },
    tier: {
      A: { en: "Settled, cited", ar: "ثابت وموثّق" },
      B: { en: "Explained from sources", ar: "شرح من المصادر" },
      C: { en: "Scholars differ", ar: "مسألة خلافية" },
      D: { en: "Personal case — referred", ar: "حالة شخصية — إحالة" },
      OUT: { en: "Outside scope", ar: "خارج النطاق" },
      NONE: { en: "No approved source found", ar: "لا يوجد مصدر معتمد" },
    },
    referralTitle: { en: "Speak to a qualified scholar", ar: "استشر عالمًا مؤهّلًا" },
    followUps: { en: "You could also ask", ar: "يمكنك أن تسأل أيضًا" },
  },

  instructor: {
    totalLessons: { en: "All lessons", ar: "كل الدروس" },
    searchTitle: { en: "Search by title", ar: "البحث بالعنوان" },
    searchPlaceholder: { en: "Search lesson titles…", ar: "ابحث في عناوين الدروس…" },
    clearSearch: { en: "Clear search", ar: "مسح البحث" },
    overview: { en: "Lesson overview", ar: "نظرة عامة على الدروس" },
    viewLesson: { en: "Lesson details", ar: "تفاصيل الدرس" },
    history: { en: "Activity history", ar: "سجل النشاط" },
    historyHint: { en: "Who changed this lesson and when. Times are shown in your local time zone.", ar: "من عدّل هذا الدرس ومتى. تُعرض الأوقات حسب منطقتك الزمنية." },
    historyEmpty: { en: "No recorded activity yet. Earlier changes were not tracked.", ar: "لا يوجد نشاط مسجّل بعد. لم تُسجّل التغييرات السابقة." },
    historyLoading: { en: "Loading activity…", ar: "جارٍ تحميل النشاط…" },
    historyError: { en: "Activity could not be loaded.", ar: "تعذّر تحميل النشاط." },
    retry: { en: "Try again", ar: "حاول مجددًا" },
    unknownActor: { en: "Unknown user", ar: "مستخدم غير معروف" },
    archive: { en: "Archive", ar: "أرشفة" },
    archived: { en: "Lesson archived.", ar: "أُرشف الدرس." },
    archiveConfirm: { en: "Archive this lesson? It will leave the library and review queue. Its content, learner progress and activity history will be kept.", ar: "هل تريد أرشفة هذا الدرس؟ سيُزال من المكتبة وقائمة المراجعة مع الاحتفاظ بالمحتوى وتقدّم المتعلّمين وسجل النشاط." },
    editArchived: { en: "Edit as draft", ar: "تحرير كمسودة" },
    noResults: { en: "No lessons match your search or filters.", ar: "لا توجد دروس تطابق البحث أو الفلاتر." },
    noResultsHint: { en: "Try another title or reset the filters to see all lessons.", ar: "جرّب عنوانًا آخر أو أعد ضبط الفلاتر لعرض كل الدروس." },
    events: {
      created: { en: "Created by", ar: "أُنشئ بواسطة" },
      updated: { en: "Updated by", ar: "عُدّل بواسطة" },
      submit: { en: "Submitted for review by", ar: "أُرسل للمراجعة بواسطة" },
      approve: { en: "Published by", ar: "نُشر بواسطة" },
      reviewed: { en: "Reviewed and published by", ar: "رُوجع ونُشر بواسطة" },
      request_changes: { en: "Changes requested by", ar: "طُلبت تعديلات بواسطة" },
      unpublish: { en: "Moved to draft by", ar: "حُوّل إلى مسودة بواسطة" },
      archived: { en: "Archived by", ar: "أُرشف بواسطة" },
      ai_check: { en: "Pre-checked by", ar: "فُحص أوليًا بواسطة" },
      other: { en: "Activity by", ar: "نشاط بواسطة" },
    },
    newLesson: { en: "New lesson", ar: "درس جديد" },
    lessonDraft: { en: "Lesson draft", ar: "مسودة الدرس" },
    draftHint: { en: "Add lesson text and source ids, then save your draft.", ar: "أضف نص الدرس ومعرّفات المصادر، ثم احفظ المسودة." },
    titleRequired: { en: "Enter both lesson titles.", ar: "أدخل عنوان الدرس باللغتين." },
    closeModal: { en: "Close", ar: "إغلاق" },
    resetFilters: { en: "Reset filters", ar: "إعادة ضبط الفلاتر" },
    colLesson: { en: "Lesson", ar: "الدرس" },
    colActions: { en: "Actions", ar: "الإجراءات" },
    pagination: { en: "Lesson pages", ar: "صفحات الدروس" },
    perPage: { en: "Lessons per page", ar: "الدروس في الصفحة" },
    actionSuccess: { en: "Success", ar: "تم بنجاح" },
    actionFailed: { en: "Action failed", ar: "تعذّر تنفيذ العملية" },
    draftReady: { en: "Starting draft ready. Add lesson text and sources before saving.", ar: "المسودة الأولية جاهزة. أضف نص الدرس والمصادر قبل الحفظ." },
    previousPage: { en: "Previous", ar: "السابق" },
    nextPage: { en: "Next", ar: "التالي" },
    page: { en: "Page", ar: "صفحة" },
    pageOf: { en: "of", ar: "من" },
    newLessonHint: { en: "Fill these details to start a JSON draft, then add card text and source ids before saving.", ar: "أدخل هذه التفاصيل لإنشاء مسودة JSON، ثم أضف نص البطاقة ومعرّفات المصادر قبل الحفظ." },
    englishTitle: { en: "English title", ar: "العنوان بالإنجليزية" },
    arabicTitle: { en: "Arabic title", ar: "العنوان بالعربية" },
    createDraft: { en: "Open starting draft", ar: "فتح المسودة الأولية" },
    track: { en: "Track", ar: "المسار" },
    module: { en: "Module", ar: "الوحدة" },
    level: { en: "Level", ar: "المستوى" },
    statusFilter: { en: "Status", ar: "الحالة" },
    minutes: { en: "Minutes", ar: "الدقائق" },
    allLevels: { en: "All levels", ar: "كل المستويات" },
    allStatuses: { en: "All statuses", ar: "كل الحالات" },
    count: { en: "Lessons shown", ar: "الدروس المعروضة" },
    publishDirect: { en: "Publish", ar: "نشر" },
    hide: { en: "Hide", ar: "إخفاء" },
    delete: { en: "Delete", ar: "حذف" },
    deleteConfirm: { en: "Delete this draft permanently? This cannot be undone.", ar: "هل تريد حذف هذه المسودة نهائيًا؟ لا يمكن التراجع عن ذلك." },
    hideReviewed: { en: "Learners will not see this lesson until an admin approves it again. All its sources must be approved first.", ar: "لن يرى المتعلّمون هذا الدرس حتى يعتمده مشرف مجددًا. يجب اعتماد جميع مصادره أولًا." },
    hidden: { en: "Lesson hidden.", ar: "أُخفي الدرس." },
    deleted: { en: "Draft deleted.", ar: "حُذفت المسودة." },
    addPlanned: { en: "Add Coming soon title", ar: "إضافة عنوان قريبًا" },
    removePlanned: { en: "Remove", ar: "إزالة" },
    plannedAdded: { en: "Coming soon title added.", ar: "أُضيف عنوان قريبًا." },
    plannedRemoved: { en: "Coming soon title removed.", ar: "أُزيل عنوان قريبًا." },
    noPlanned: { en: "No Coming soon titles.", ar: "لا توجد عناوين قادمة." },
    reviewMode: { en: "Submit your lessons for admin review before publication.", ar: "أرسل دروسك لمراجعة المشرف قبل النشر." },
    closeForm: { en: "Cancel", ar: "إلغاء" },
    status: {
      draft: { en: "Draft", ar: "مسودة" },
      in_review: { en: "In review", ar: "قيد المراجعة" },
      published: { en: "Published", ar: "منشور" },
      archived: { en: "Archived", ar: "مؤرشف" },
    },
    drafts: { en: "Drafts and lesson reviews", ar: "المسودات ومراجعة الدروس" },
    reviewNote: { en: "Review note", ar: "ملاحظة المراجعة" },
    edit: { en: "Edit", ar: "تحرير" },
    submitted: { en: "Submitted for review.", ar: "أُرسل للمراجعة." },
    submit: { en: "Submit for review", ar: "إرسال للمراجعة" },
    published: { en: "Lesson published.", ar: "نُشر الدرس." },
    publish: { en: "Approve and publish", ar: "اعتماد ونشر" },
    changesRequested: { en: "Changes requested.", ar: "طُلبت تعديلات." },
    requestChanges: { en: "Request changes", ar: "طلب تعديلات" },
    noDrafts: { en: "No drafts yet. Use a sample below and give the new lesson a unique id.", ar: "لا توجد مسودات. استخدم النموذج أدناه وحدّد معرّفًا جديدًا للدرس." },
    draftSaved: { en: "Draft saved.", ar: "حُفظت المسودة." },
    saveDraft: { en: "Save draft", ar: "حفظ المسودة" },
    unavailable: { en: "Course editing will be available soon. You can browse published lessons in the library.", ar: "سيُتاح تحرير الدورات قريبًا. يمكنك تصفّح الدروس المنشورة في المكتبة." },
    sourceApproved: { en: "Source approved.", ar: "اعتُمد المصدر." },
    approveSource: { en: "Approve verified source", ar: "اعتماد المصدر بعد التحقق" },
    lessons: { en: "Lessons", ar: "الدروس" },
    sources: { en: "Sources", ar: "المصادر" },
    backToApp: { en: "Back to app", ar: "العودة إلى التطبيق" },
    navigation: { en: "Studio navigation", ar: "التنقل في الاستوديو" },
    pending: { en: "Pending", ar: "بانتظار المراجعة" },
    sample: { en: "Sample", ar: "نموذج" },
    readyForReview: { en: "Ready for scholarly review", ar: "جاهز للمراجعة العلمية" },
    needsChanges: { en: "Needs changes before review", ar: "يحتاج إلى تعديلات قبل المراجعة" },
    title: { en: "Studio", ar: "الاستوديو" },
    sub: {
      en: "Manage lesson drafts and review content before publication.",
      ar: "أدِر مسودات الدروس وراجع المحتوى قبل النشر.",
    },
    queue: { en: "Review queue", ar: "قائمة المراجعة" },
    sourcesPending: { en: "Sources awaiting review", ar: "مصادر بانتظار المراجعة" },
    lessonsPublished: { en: "Published lessons", ar: "دروس منشورة" },
    aiCheck: { en: "AI pre-check", ar: "فحص أوّلي بالذكاء الاصطناعي" },
    aiCheckSub: {
      en: "Paste a lesson draft (JSON). We verify every citation exists and flag scripture that isn't from a stored source.",
      ar: "الصق مسودة درس (JSON). نتحقّق من وجود كل مصدر، وننبّه على أي نص يشبه النص الشرعي وليس من مصدر مخزّن.",
    },
    run: { en: "Run pre-check", ar: "شغّل الفحص" },
    approve: { en: "Approve", ar: "اعتمد" },
    changes: { en: "Request changes", ar: "اطلب تعديلات" },
    restricted: {
      en: "This workspace is for teachers and admins. Sign in with an approved staff account.",
      ar: "هذه المساحة للمعلّمين والمشرفين. سجّل الدخول بحساب فريق معتمد.",
    },
  },

  editor: {
    back: { en: "Back to lessons", ar: "العودة إلى الدروس" },
    leave: { en: "Leave without saving? Your changes will be lost.", ar: "هل تريد المغادرة دون حفظ؟ ستفقد تغييراتك." },
    startTitle: { en: "How do you want to start?", ar: "كيف تريد أن تبدأ؟" },
    startSub: { en: "Both ways open the same editor. You can change everything before you save.", ar: "الطريقتان تفتحان المحرّر نفسه، ويمكنك تعديل كل شيء قبل الحفظ." },
    manual: { en: "Write it yourself", ar: "اكتبه بنفسك" },
    manualSub: { en: "Start with an empty lesson. Add your pages and quotes.", ar: "ابدأ بدرس فارغ، ثم أضف الصفحات والاقتباسات." },
    ai: { en: "Generate with AI", ar: "أنشئه بالذكاء الاصطناعي" },
    aiSub: { en: "Describe the lesson. AI writes a first draft, then you review and edit it.", ar: "صِف الدرس، فيكتب الذكاء الاصطناعي مسودة أولى، ثم تراجعها وتعدّلها." },
    aiTitle: { en: "Describe your lesson", ar: "صِف درسك" },
    aiHint: { en: "Say the topic, who it is for and what it must cover. Nothing is published before you review it.", ar: "اذكر الموضوع والفئة المقصودة وما يجب أن يتناوله الدرس. لا يُنشر شيء قبل مراجعتك." },
    aiPlaceholder: { en: "Example: A short lesson for new Muslims about what breaks wudu, with the main evidence.", ar: "مثال: درس قصير للمسلمين الجدد عن نواقض الوضوء مع أهم الأدلة." },
    aiExamples: [
      { en: "The five pillars of Islam, for someone curious about Islam", ar: "أركان الإسلام الخمسة لمن يريد التعرّف على الإسلام" },
      { en: "How to pray two rak'ahs, step by step, for a new Muslim", ar: "كيفية صلاة ركعتين خطوة بخطوة للمسلم الجديد" },
      { en: "The meaning of Surah Al-Ikhlas, verse by verse", ar: "معاني سورة الإخلاص آيةً آية" },
    ],
    generate: { en: "Generate draft", ar: "إنشاء المسودة" },
    generating: { en: "Writing your draft…", ar: "جارٍ كتابة المسودة…" },
    aiPending: { en: "AI drafting is not connected yet, so this lesson starts empty. Your description is kept here to guide you:", ar: "لم يُفعَّل الإنشاء بالذكاء الاصطناعي بعد، لذلك يبدأ هذا الدرس فارغًا. احتفظنا بوصفك هنا ليساعدك:" },
    aiReady: { en: "This is an AI first draft. Review every page and its sources before saving.", ar: "هذه مسودة أولى من الذكاء الاصطناعي. راجع كل صفحة ومصادرها قبل الحفظ." },
    contentLang: { en: "Content language", ar: "لغة المحتوى" },
    langHint: { en: "Write in one language or both. Learners see the language that exists.", ar: "اكتب بلغة واحدة أو باللغتين. يرى المتعلّم اللغة المتوفّرة." },
    langComplete: { en: "complete", ar: "مكتملة" },
    remove: { en: "Remove", ar: "إزالة" },
    titlePlaceholder: { en: "Lesson title", ar: "عنوان الدرس" },
    summary: { en: "Summary", ar: "الملخّص" },
    pages: { en: "Lesson pages", ar: "صفحات الدرس" },
    tags: { en: "Tags", ar: "الوسوم" },
    tagAdd: { en: "Add a tag, then press Enter", ar: "أضف وسمًا ثم اضغط Enter" },
    summaryPlaceholder: { en: "Short summary shown in the library (one or two sentences)", ar: "ملخّص قصير يظهر في المكتبة (جملة أو جملتان)" },
    section: { en: "Page", ar: "الصفحة" },
    sectionTitle: { en: "Page title", ar: "عنوان الصفحة" },
    sectionBody: { en: "Write this page…", ar: "اكتب هذه الصفحة…" },
    takeaway: { en: "Key takeaway (optional)", ar: "الخلاصة (اختياري)" },
    quote: { en: "Qur'an quote", ar: "اقتباس من القرآن" },
    quoteTitle: { en: "Quote title", ar: "عنوان الاقتباس" },
    quoteNote: { en: "Note under the quote (optional)", ar: "تعليق تحت الاقتباس (اختياري)" },
    quoteEmpty: { en: "Choose the verse to quote. Its text comes from the Qur'an, word for word.", ar: "اختر الآية التي تريد اقتباسها. يُعرض نصها من القرآن كما هو." },
    chooseQuote: { en: "Choose a verse", ar: "اختر آية" },
    change: { en: "Change", ar: "تغيير" },
    addSection: { en: "Add page", ar: "إضافة صفحة" },
    addQuote: { en: "Add Qur'an quote", ar: "إضافة اقتباس من القرآن" },
    moveUp: { en: "Move earlier", ar: "تقديم الصفحة" },
    moveDown: { en: "Move later", ar: "تأخير الصفحة" },
    addSource: { en: "Add source", ar: "إضافة مصدر" },
    sourceHint: { en: "Every page cites at least one source.", ar: "كل صفحة تستند إلى مصدر واحد على الأقل." },
    pickerTitle: { en: "Choose a verse", ar: "اختر آية" },
    pickerSearch: { en: "Search the Qur'an by text or verse number (6:20)…", ar: "ابحث في القرآن بالنص أو برقم الآية (6:20)…" },
    pickerLoadError: { en: "The Qur'an text could not be loaded. Close this window and try again.", ar: "تعذّر تحميل نص القرآن. أغلق هذه النافذة وحاول مجددًا." },
    pickerAddError: { en: "This verse could not be added. Try again.", ar: "تعذّرت إضافة هذه الآية. حاول مجددًا." },
    pickerEmpty: { en: "No verse matches your search.", ar: "لا توجد آية تطابق بحثك." },
    pickerMore: { en: "Showing the first results. Type more to narrow the list.", ar: "نعرض النتائج الأولى. اكتب أكثر لتضييق القائمة." },
    details: { en: "Lesson details", ar: "تفاصيل الدرس" },
    minutes: { en: "Reading time (minutes)", ar: "مدة القراءة (بالدقائق)" },
    contributors: { en: "Contributors", ar: "المساهمون" },
    contributorsHint: { en: "Nobody yet. Each account that saves this lesson is added here, by its email address.", ar: "لا أحد بعد. يُضاف هنا كل حساب يحفظ هذا الدرس بعنوان بريده الإلكتروني." },
    activity: { en: "Activity", ar: "النشاط" },
    notRecorded: { en: "Not recorded yet", ar: "غير مسجّل بعد" },
    lastUpdated: { en: "Last updated", ar: "آخر تحديث" },
    lastUpdatedBy: { en: "Updated by", ar: "آخر من حدّثه" },
    notSaved: { en: "Not saved yet", ar: "لم يُحفظ بعد" },
    unsaved: { en: "Unsaved changes", ar: "تغييرات غير محفوظة" },
    saved: { en: "All changes saved", ar: "حُفظت كل التغييرات" },
    working: { en: "Checking and saving… this can take a moment.", ar: "جارٍ الفحص والحفظ… قد يستغرق ذلك لحظات." },
    live: { en: "Live for learners. Edit anything, then update.", ar: "منشور للمتعلّمين. عدّل ما تشاء ثم حدّث." },
    update: { en: "Update lesson", ar: "تحديث الدرس" },
    updated: { en: "Lesson updated.", ar: "حُدّث الدرس." },
    liveKept: { en: "The live lesson was not changed.", ar: "لم يتغيّر الدرس المنشور." },
    view: { en: "View lesson", ar: "عرض الدرس" },
    keepEditing: { en: "Back to editing", ar: "العودة إلى التحرير" },
    previewNote: { en: "Preview: what learners see", ar: "معاينة: ما يراه المتعلّمون" },
    authorPublishes: { en: "Only the author or an admin can publish this lesson.", ar: "لا ينشر هذا الدرس إلا مؤلّفه أو مشرف." },
    fixFirst: { en: "To finish before saving", ar: "أكمل الآتي قبل الحفظ" },
    issues: { en: "The review check found problems to fix", ar: "أظهر فحص المراجعة ملاحظات يجب معالجتها" },
    needTitle: { en: "Add a lesson title.", ar: "أضف عنوان الدرس." },
    needSummary: { en: "Add a short summary.", ar: "أضف ملخّصًا قصيرًا." },
    needModule: { en: "Choose a track and module.", ar: "اختر المسار والوحدة." },
    needMinutes: { en: "Set the reading time.", ar: "حدّد مدة القراءة." },
    needSection: { en: "Add at least one page.", ar: "أضف صفحة واحدة على الأقل." },
    needsTitle: { en: "needs a title.", ar: "تحتاج إلى عنوان." },
    needsText: { en: "needs text.", ar: "تحتاج إلى نص." },
    needsSource: { en: "needs a source.", ar: "تحتاج إلى مصدر." },
    loadError: { en: "This lesson could not be opened.", ar: "تعذّر فتح هذا الدرس." },
    tools: {
      toolbar: { en: "Text formatting", ar: "تنسيق النص" },
      bold: { en: "Bold", ar: "غامق" },
      italic: { en: "Italic", ar: "مائل" },
      underline: { en: "Underline", ar: "تسطير" },
      heading: { en: "Heading", ar: "عنوان فرعي" },
      bullets: { en: "Bulleted list", ar: "قائمة نقطية" },
      numbers: { en: "Numbered list", ar: "قائمة مرقّمة" },
      callout: { en: "Highlight box", ar: "إطار تمييز" },
      color: { en: "Text color", ar: "لون النص" },
      font: { en: "Font", ar: "الخط" },
      size: { en: "Size", ar: "الحجم" },
      clear: { en: "Clear formatting", ar: "مسح التنسيق" },
      tones: {
        gold: { en: "Gold box", ar: "إطار ذهبي" },
        blue: { en: "Blue box", ar: "إطار أزرق" },
        green: { en: "Green box", ar: "إطار أخضر" },
        red: { en: "Red box", ar: "إطار أحمر" },
        gray: { en: "Gray box", ar: "إطار رمادي" },
        none: { en: "No box", ar: "بلا إطار" },
      },
      fonts: {
        inherit: { en: "Default", ar: "الافتراضي" },
        serif: { en: "Serif", ar: "سيريف" },
        naskh: { en: "Naskh (Arabic)", ar: "النسخ" },
        monospace: { en: "Monospace", ar: "ثابت العرض" },
      },
      sizes: {
        2: { en: "Small", ar: "صغير" },
        3: { en: "Normal", ar: "عادي" },
        5: { en: "Large", ar: "كبير" },
        6: { en: "Extra large", ar: "كبير جدًا" },
      },
    },
  },

  quran: {
    tafsir: { en: "Explanation", ar: "التفسير" },
    noTafsir: { en: "The Al-Mukhtasar explanation is not available in", ar: "تفسير المختصر غير متاح باللغة" },
    noVerseTafsir: { en: "The published snapshot has no explanation for this verse.", ar: "لا تحتوي النسخة المنشورة على تفسير لهذه الآية." },
    coversVerses: { en: "This passage covers verses", ar: "يشمل هذا المقطع الآيات" },
    dumpVersion: { en: "dump/catalogue version", ar: "نسخة البيانات / الفهرس" },
    tafsirError: { en: "The explanation could not be loaded. Check your connection and try again.", ar: "تعذّر تحميل التفسير. تحقّق من اتصالك ثم أعد المحاولة." },
    sub: { en: "Read the Quran with a translation of its meanings, verse by verse.", ar: "اقرأ القرآن مع ترجمة معانيه آيةً آية." },
    translation: { en: "Translation", ar: "الترجمة" },
    search: { en: "Search the selected text, or type 2:255", ar: "ابحث في النص المختار، أو اكتب 2:255" },
    searchScope: { en: "Search in", ar: "البحث في" },
    searchFr: { en: "Search the translation, or type 2:255", ar: "ابحث في الترجمة، أو اكتب 2:255" },
    clear: { en: "Clear search", ar: "مسح البحث" },
    found: { en: "verses found", ar: "آية مطابقة" },
    foundOne: { en: "verse found", ar: "آية مطابقة" },
    none: { en: "No verse found. Try fewer or different words.", ar: "لا توجد آية مطابقة. جرّب كلمات أقل أو مختلفة." },
    tooShort: { en: "Type at least two letters.", ar: "اكتب حرفين على الأقل." },
    surah: { en: "Surah", ar: "سورة" },
    findSurah: { en: "Find a surah by name or number", ar: "ابحث عن سورة بالاسم أو الرقم" },
    noSurah: { en: "No surah matches.", ar: "لا توجد سورة مطابقة." },
    verse: { en: "Verse", ar: "الآية" },
    verses: { en: "verses", ar: "آية" },
    page: { en: "Page", ar: "الصفحة" },
    pages: { en: "Pages", ar: "الصفحات" },
    juz: { en: "Juz", ar: "الجزء" },
    display: { en: "Text shown", ar: "النص المعروض" },
    both: { en: "Both", ar: "معًا" },
    prev: { en: "Previous surah", ar: "السورة السابقة" },
    next: { en: "Next surah", ar: "السورة التالية" },
    arabicText: { en: "Arabic text:", ar: "النص العربي:" },
    attribution: { en: "Translation of the meanings:", ar: "ترجمة المعاني:" },
    version: { en: "catalogue version", ar: "نسخة الفهرس" },
    openSource: { en: "Open this surah at the source", ar: "افتح السورة في المصدر" },
    error: { en: "The Quran text could not be loaded. Check your connection and try again.", ar: "تعذّر تحميل نص القرآن. تحقّق من اتصالك ثم أعد المحاولة." },
    retry: { en: "Try again", ar: "أعد المحاولة" },
    listen: { en: "Listen to the surah", ar: "استمع إلى السورة" },
    pause: { en: "Pause the recitation", ar: "أوقف التلاوة مؤقتًا" },
    playVerse: { en: "Listen to verse", ar: "استمع إلى الآية" },
    recitation: { en: "Recitation:", ar: "التلاوة:" },
    hafs: { en: "Hafs from Asim", ar: "حفص عن عاصم" },
    noAudio: { en: "Recitation is not available for this surah.", ar: "التلاوة غير متاحة لهذه السورة." },
    audioError: { en: "The recitation could not be played. Check your connection and try again.", ar: "تعذّر تشغيل التلاوة. تحقّق من اتصالك ثم أعد المحاولة." },
  },

  compare: {
    intro: {
      en: "Explore other beliefs and see how each one compares with Islam. Choose a belief, then a topic.",
      ar: "استكشف المعتقدات الأخرى وتعرّف على مقارنة كلٍّ منها بالإسلام. اختر معتقدًا ثم موضوعًا.",
    },
    reference: { en: "Reference", ar: "المرجع" },
    referenceNote: { en: "Islam is the reference for every comparison.", ar: "الإسلام هو المرجع في كل مقارنة." },
    comparedWith: { en: "Compared with Islam", ar: "مقارنةً بالإسلام" },
    topics: { en: "Comparison topics", ar: "موضوعات المقارنة" },
    traditions: { en: "Traditions", ar: "المذاهب والطوائف" },
    pickTopic: { en: "Choose a topic to open its comparison.", ar: "اختر موضوعًا لفتح مقارنته." },
    breadcrumb: { en: "Breadcrumb", ar: "مسار التنقل" },
    overview: { en: "Overview", ar: "نظرة عامة" },
    back: { en: "Back", ar: "رجوع" },
    islamic: { en: "Islamic perspective", ar: "المنظور الإسلامي" },
    placeholder: { en: "Content will be added after review.", ar: "سيُضاف المحتوى بعد المراجعة." },
    status: {
      draft: { en: "In preparation", ar: "قيد الإعداد" },
      in_review: { en: "In review", ar: "قيد المراجعة" },
      published: { en: "Reviewed", ar: "تمت المراجعة" },
      archived: { en: "Archived", ar: "مؤرشف" },
    },
    sections: {
      overview: { en: "Short overview", ar: "نبذة مختصرة" },
      beliefs: { en: "Main beliefs", ar: "المعتقدات الأساسية" },
      common: { en: "Common ground", ar: "القواسم المشتركة" },
      differences: { en: "Key differences", ar: "أبرز الفروق" },
      faq: { en: "Frequently asked questions", ar: "الأسئلة الشائعة" },
      sources: { en: "Sources and references", ar: "المصادر والمراجع" },
    },
  },

  users: {
    title: { en: "Users", ar: "المستخدمون" },
    sub: { en: "Staff sign up as learners. Search for their account and assign a role.", ar: "يسجّل أعضاء الفريق كمتعلّمين. ابحث عن حساباتهم ثم حدّد أدوارهم." },
    restricted: { en: "User management requires a super admin account.", ar: "تتطلّب إدارة المستخدمين حساب مشرف عام." },
    searchLabel: { en: "Email or name", ar: "البريد الإلكتروني أو الاسم" },
    search: { en: "Search", ar: "بحث" },
    results: { en: "Users (up to 50)", ar: "المستخدمون (حتى ٥٠)" },
    empty: { en: "No users found.", ar: "لم يُعثر على مستخدمين." },
    role: { en: "Role", ar: "الدور" },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Role saved.", ar: "حُفظ الدور." },
    self: { en: "You cannot change your own role.", ar: "لا يمكنك تغيير دورك." },
    unavailable: { en: "User management is currently unavailable. Please try again later.", ar: "إدارة المستخدمين غير متاحة حاليًا. يُرجى المحاولة لاحقًا." },
    roles: {
      learner: { en: "Learner", ar: "متعلّم" },
      teacher: { en: "Teacher", ar: "معلّم" },
      admin: { en: "Admin", ar: "مشرف" },
      super_admin: { en: "Super admin", ar: "مشرف عام" },
    },
  },

  common: {
    loading: { en: "Loading…", ar: "جارٍ التحميل…" },
    aiLabel: { en: "AI", ar: "ذكاء اصطناعي" },
    close: { en: "Close", ar: "إغلاق" },
    lang: { en: "العربية", ar: "English" },
  },
} satisfies Record<string, unknown>;

export type Strings = typeof S;
export type { Bi };
