import type { Bi } from "./types";

// UI copy. Content strings (lessons, sources) live in ../content.
export const S = {
  brandTagline: { en: "Knowledge that brings you closer", ar: "علمٌ يقرّبك" },
  motto: { en: "Learn · Reflect · Live it", ar: "علمٌ أعمق .. حياةٌ أقرب" },

  nav: {
    home: { en: "Home", ar: "الرئيسية" },
    learn: { en: "Learn", ar: "تعلّم" },
    library: { en: "Library", ar: "المكتبة" },
    quran: { en: "Quran & Translations", ar: "القرآن والترجمات" },
    quranShort: { en: "Quran", ar: "القرآن" },
    ask: { en: "Ask & Check", ar: "اسأل وتحقّق" },
    compare: { en: "Religion & Belief Comparison", ar: "مقارنة الأديان والمعتقدات" },
    compareShort: { en: "Compare", ar: "مقارنة" },
    sources: { en: "Our sources", ar: "مصادرنا" },
    educators: { en: "For educators", ar: "للمعلّمين" },
    signIn: { en: "Sign in", ar: "تسجيل الدخول" },
    getStarted: { en: "Get started", ar: "ابدأ الآن" },
    dashboard: { en: "Dashboard", ar: "لوحتي" },
    myLearning: { en: "My learning", ar: "تعلّمي" },
    instructor: { en: "Studio", ar: "الاستوديو" },
    signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  },

  hero: {
    eyebrow: { en: "Knowledge that brings you closer", ar: "علمٌ يقرّبك" },
    title1: { en: "Understand Islam,", ar: "افهم الإسلام" },
    title2: { en: "one clear step at a time", ar: "خطوةً واضحةً بعد خطوة" },
    sub: {
      en: "Short visual lessons you can listen to and talk to, in Arabic and English, with every claim traceable to an approved source.",
      ar: "دروس بصرية قصيرة تستمع إليها وتحاورها، بالعربية والإنجليزية، وكل معلومة فيها مرتبطة بمصدرها المعتمد.",
    },
    cta: { en: "Start learning free", ar: "ابدأ التعلّم مجانًا" },
    cta2: { en: "Try the tutor", ar: "جرّب المعلّم" },
  },

  pillars: {
    sources: { en: "Approved sources", ar: "مصادر معتمدة" },
    sourcesSub: { en: "Qur'an · Hadith · Scholarship", ar: "القرآن · الحديث · أهل العلم" },
    ai: { en: "Grounded AI", ar: "ذكاء اصطناعي منضبط" },
    aiSub: { en: "Answers only from sources", ar: "يجيب من المصادر فقط" },
    everyone: { en: "For every learner", ar: "لكل متعلّم" },
    everyoneSub: { en: "Curious · New · Deepening", ar: "باحث · مسلم جديد · متعمّق" },
    langs: { en: "Bilingual", ar: "ثنائي اللغة" },
    langsSub: { en: "العربية · English", ar: "العربية · English" },
  },

  journey: {
    title: { en: "Begin your journey", ar: "ابدأ رحلتك" },
    sub: {
      en: "Three paths, one scholarly reference. Pick the one that fits you today — you can switch any time.",
      ar: "ثلاثة مسارات ومرجعية علمية واحدة. اختر ما يناسبك اليوم، ويمكنك التبديل متى شئت.",
    },
    open: { en: "Open track", ar: "افتح المسار" },
  },

  trust: {
    title: { en: "Built on approved, traceable sources", ar: "مبنيّ على مصادر معتمدة يمكن تتبّعها" },
    sub: {
      en: "We follow the challenge's scholarly reference. Revealed text is shown verbatim — never generated.",
      ar: "نلتزم بالمرجعية العلمية للتحدي. يُعرض النص الشرعي بنصّه، ولا يُولَّد أبدًا.",
    },
    quran: { en: "Qur'an", ar: "القرآن الكريم" },
    quranSub: { en: "Verified Uthmani text", ar: "النص العثماني الموثّق" },
    hadith: { en: "Sahih hadith", ar: "الحديث الصحيح" },
    hadithSub: { en: "With collection and grading", ar: "مع المصدر والحكم" },
    tafsir: { en: "Tafsir", ar: "التفسير" },
    tafsirSub: { en: "Classical explanation", ar: "شروح أهل العلم" },
    review: { en: "Human review", ar: "مراجعة علمية" },
    reviewSub: { en: "Every lesson approved", ar: "كل درس معتمد" },
    levels: { en: "Four answer levels", ar: "أربعة مستويات للإجابة" },
    levelsSub: { en: "Cite · explain · note differences · refer", ar: "توثيق · شرح · بيان الخلاف · إحالة" },
  },

  features: {
    title: { en: "A clearer way to learn", ar: "طريقة أوضح للتعلّم" },
    sub: { en: "Modern tools, faithful to the sources.", ar: "أدوات حديثة، أمينة على المصادر." },
    lessons: { en: "Visual micro-lessons", ar: "دروس بصرية قصيرة" },
    lessonsSub: {
      en: "One idea per card, an illustration, a takeaway — read or listen.",
      ar: "فكرة واحدة في كل بطاقة، مع صورة وخلاصة — اقرأ أو استمع.",
    },
    tutor: { en: "Ask & Check tutor", ar: "معلّم «اسأل وتحقّق»" },
    tutorSub: {
      en: "Ask by voice or text. It cites its sources, or says it can't.",
      ar: "اسأل بالصوت أو النص. يذكر مصادره، أو يخبرك أنه لا يملك مصدرًا.",
    },
    explain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    explainSub: {
      en: "Explain an idea out loud; we show what you missed and why.",
      ar: "اشرح الفكرة بصوتك، فنبيّن لك ما فاتك ودليله.",
    },
    progress: { en: "Steady progress", ar: "تقدّم ثابت" },
    progressSub: {
      en: "Today's plan, reviews and streaks — tracking learning, never faith.",
      ar: "خطة اليوم والمراجعة والاستمرارية — نتابع التعلّم، لا الإيمان.",
    },
  },

  promise: {
    title: { en: "Our promise to learners", ar: "عهدنا مع المتعلّمين" },
    p1: { en: "No answer without a source — or an honest “I don't know”.", ar: "لا إجابة بلا مصدر — أو «لا أعلم» بصدق." },
    p2: { en: "No personal fatwa. Personal cases go to a qualified scholar.", ar: "لا فتوى شخصية. تُحال الحالات الخاصة إلى عالم مؤهّل." },
    p3: { en: "We never infer or store your beliefs.", ar: "لا نستنتج قناعاتك ولا نخزّنها." },
    p4: { en: "Every lesson is reviewed by a person before it is published.", ar: "كل درس يراجعه إنسان قبل نشره." },
  },

  footer: {
    line: { en: "One platform. A clearer path.", ar: "منصة واحدة. طريق أوضح." },
    about: { en: "About", ar: "عن يقين" },
    privacy: { en: "Privacy", ar: "الخصوصية" },
    method: { en: "Our method", ar: "منهجنا" },
    ai: {
      en: "Yaqin uses AI. Explanations are AI-assisted and reviewed; revealed text is shown verbatim from approved sources.",
      ar: "يستخدم «يقين» الذكاء الاصطناعي. الشروح مدعومة به ومراجَعة، والنص الشرعي يُعرض بنصّه من المصادر المعتمدة.",
    },
  },

  auth: {
    welcome: { en: "Welcome back", ar: "أهلًا بعودتك" },
    welcomeSub: { en: "Sign in to continue your journey with Yaqin.", ar: "سجّل الدخول لمتابعة رحلتك مع يقين." },
    create: { en: "Create your account", ar: "أنشئ حسابك" },
    createSub: { en: "Save your progress across devices.", ar: "احفظ تقدّمك على كل أجهزتك." },
    email: { en: "Email address", ar: "البريد الإلكتروني" },
    password: { en: "Password", ar: "كلمة المرور" },
    name: { en: "Your name", ar: "اسمك" },
    remember: { en: "Remember me", ar: "تذكّرني" },
    forgot: { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
    signIn: { en: "Sign in", ar: "تسجيل الدخول" },
    signUp: { en: "Create account", ar: "إنشاء الحساب" },
    or: { en: "or", ar: "أو" },
    google: { en: "Continue with Google", ar: "المتابعة عبر Google" },
    guest: { en: "Continue as guest", ar: "المتابعة كزائر" },
    guestSub: { en: "Explore lessons without an account", ar: "استكشف الدروس دون حساب" },
    noAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
    haveAccount: { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
    checkEmail: { en: "Check your email to confirm your account.", ar: "تحقّق من بريدك لتأكيد الحساب." },
    resetSent: { en: "If that email exists, a reset link is on its way.", ar: "إن كان البريد مسجّلًا فسيصلك رابط إعادة التعيين." },
    unavailable: {
      en: "Accounts are not configured on this deployment yet — continue as a guest.",
      ar: "الحسابات غير مفعّلة في هذه النسخة بعد — تابع كزائر.",
    },
    sideTitle1: { en: "Deeper learning,", ar: "تعلّمٌ أعمق" },
    sideTitle2: { en: "a brighter tomorrow", ar: "وغدٌ أنقى" },
    sideSub: {
      en: "Learn with approved Islamic sources, guided by grounded AI, for a more conscious and confident you.",
      ar: "تعلّم من مصادر إسلامية معتمدة، بإرشاد ذكاء اصطناعي منضبط، لتزداد وعيًا وثقة.",
    },
  },

  onboarding: {
    step: { en: "Step", ar: "الخطوة" },
    of: { en: "of", ar: "من" },
    trackQ: { en: "Where would you like to start?", ar: "من أين تحبّ أن تبدأ؟" },
    trackHint: {
      en: "This only chooses your lessons. We don't record anything about your beliefs.",
      ar: "هذا يحدّد دروسك فقط. لا نسجّل شيئًا عن قناعاتك.",
    },
    langQ: { en: "Which language do you prefer?", ar: "ما اللغة التي تفضّلها؟" },
    timeQ: { en: "How much time per day?", ar: "كم من الوقت يوميًا؟" },
    minutes: { en: "min / day", ar: "دقيقة يوميًا" },
    checkQ: { en: "A quick check, to find your starting point", ar: "اختبار سريع لتحديد نقطة البداية" },
    checkHint: { en: "It's fine to skip or guess.", ar: "لا بأس أن تتخطّى أو تخمّن." },
    skip: { en: "Skip", ar: "تخطَّ" },
    next: { en: "Next", ar: "التالي" },
    back: { en: "Back", ar: "رجوع" },
    finish: { en: "Show my plan", ar: "اعرض خطتي" },
  },

  dash: {
    // Greeting per track: "explore" learners may not be Muslim, so no religious salutation.
    greeting: {
      explore: {
        hello: { en: "Welcome", ar: "أهلًا بك" },
        sub: { en: "Explore Islam at your own pace, with clear answers from trusted sources.", ar: "اكتشف الإسلام على مهلك، بإجابات واضحة من مصادر موثوقة." },
      },
      "first-steps": {
        hello: { en: "Assalamu alaikum", ar: "السلام عليكم" },
        sub: { en: "Welcome to your first steps. One small, clear step at a time.", ar: "مرحبًا بك في خطواتك الأولى. خطوة صغيرة واضحة كل مرة." },
      },
      deepen: {
        hello: { en: "Assalamu alaikum", ar: "السلام عليكم" },
        sub: { en: "May your pursuit of knowledge be a means of barakah.", ar: "جعل الله طلبك للعلم سببًا للبركة." },
      },
    },
    yourTrack: { en: "Your track", ar: "مسارك" },
    today: { en: "Today's plan", ar: "خطة اليوم" },
    completed: { en: "completed", ar: "مكتمل" },
    journey: { en: "Your learning journey", ar: "رحلتك التعليمية" },
    level: { en: "Level", ar: "المستوى" },
    comingSoon: { en: "Coming soon", ar: "قريبًا" },
    locked: { en: "Finish the previous level to unlock", ar: "أكمل المستوى السابق لفتحه" },
    prevLevel: { en: "Previous level", ar: "المستوى السابق" },
    nextLevel: { en: "Next level", ar: "المستوى التالي" },
    road: {
      done: { en: "Completed", ar: "مكتمل" },
      now: { en: "In progress", ar: "قيد التعلّم" },
      planned: { en: "Planned", ar: "مخطّط" },
    },
    streak: { en: "Day streak", ar: "أيام متتالية" },
    streakHint: {
      en: "The number of days in a row you've learned.",
      ar: "عدد الأيام المتتالية التي تعلّمت فيها.",
    },
    lessonsDone: { en: "Lessons completed", ar: "دروس مكتملة" },
    continue: { en: "Continue", ar: "تابع" },
    start: { en: "Start", ar: "ابدأ" },
    review: { en: "Review", ar: "راجع" },
    guestNote: {
      en: "You're learning as a guest. Progress is saved on this device only.",
      ar: "أنت تتعلّم كزائر. يُحفظ تقدّمك على هذا الجهاز فقط.",
    },
    saveProgress: { en: "Create an account to save it", ar: "أنشئ حسابًا لحفظه" },
    stages: {
      foundations: { en: "Foundations", ar: "الأساس" },
      understanding: { en: "Understanding", ar: "الفهم" },
      practice: { en: "Practice", ar: "التطبيق" },
      impact: { en: "Living it", ar: "العمل به" },
    },
    planRead: { en: "Read", ar: "اقرأ" },
    planExplain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    planQuiz: { en: "Quick check", ar: "اختبار قصير" },
    planAsk: { en: "Ask one question you've wondered about", ar: "اسأل سؤالًا شغلك" },
  },

  library: {
    title: { en: "Lessons library", ar: "مكتبة الدروس" },
    sub: { en: "Explore. Discover. Learn what matters.", ar: "استكشف، واكتشف، وتعلّم ما يهمّك." },
    search: { en: "Search lessons or topics…", ar: "ابحث في الدروس أو الموضوعات…" },
    all: { en: "All tracks", ar: "كل المسارات" },
    filter: { en: "Filter by track", ar: "تصفية حسب المسار" },
    views: { en: "Library views", ar: "طرق عرض المكتبة" },
    learnTab: { en: "Learn Islam", ar: "تعلّم الإسلام" },
    browseTab: { en: "Browse lessons", ar: "تصفّح الدروس" },
    learnTitle: { en: "Start exploring Islam.", ar: "ابدأ اكتشاف الإسلام." },
    learnSub: { en: "Learn the basics, one step at a time.", ar: "تعلّم الأساسيات، خطوة بخطوة." },
    startLearning: { en: "Start learning", ar: "ابدأ التعلّم" },
    continueLearning: { en: "Continue learning", ar: "تابع التعلّم" },
    allDone: { en: "You have completed every available lesson.", ar: "أكملت جميع الدروس المتاحة." },
    notStarted: { en: "Not started", ar: "لم يبدأ بعد" },
    recommended: { en: "Recommended next", ar: "الدرس التالي المقترح" },
    askHint: { en: "Have a question about what you read?", ar: "هل لديك سؤال عمّا قرأت؟" },
    lessons: { en: "lessons", ar: "دروس" },
    cards: { en: "cards", ar: "بطاقات" },
    min: { en: "min", ar: "د" },
    foundation: { en: "Foundation", ar: "تمهيدي" },
    deeper: { en: "Deeper", ar: "متعمّق" },
    empty: { en: "No lessons match that search yet.", ar: "لا توجد دروس مطابقة بعد." },
  },

  lesson: {
    back: { en: "Back to library", ar: "العودة إلى المكتبة" },
    of: { en: "of", ar: "من" },
    listen: { en: "Listen", ar: "استمع" },
    pause: { en: "Pause", ar: "إيقاف" },
    sources: { en: "Sources", ar: "المصادر" },
    ask: { en: "Ask the tutor", ar: "اسأل المعلّم" },
    continue: { en: "Continue", ar: "متابعة" },
    previous: { en: "Previous", ar: "السابق" },
    revealed: { en: "Revealed text", ar: "نص شرعي" },
    generated: { en: "AI-assisted explanation · reviewed", ar: "شرح مدعوم بالذكاء الاصطناعي · مُراجَع" },
    pendingReview: { en: "Source pending scholarly review", ar: "المصدر بانتظار المراجعة العلمية" },
    obligatory: { en: "Obligatory", ar: "واجب" },
    recommended: { en: "Recommended", ar: "مستحب" },
    suggestion: { en: "Learning suggestion", ar: "اقتراح تعلّم" },
    explainTitle: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    explainHint: {
      en: "Say it out loud or type it. There's no grade — this just shows what to review.",
      ar: "قلها بصوتك أو اكتبها. لا درجات هنا — نبيّن لك فقط ما تراجعه.",
    },
    record: { en: "Record", ar: "سجّل" },
    stop: { en: "Stop", ar: "أوقف" },
    typeInstead: { en: "…or type your explanation", ar: "…أو اكتب شرحك" },
    check: { en: "Check my explanation", ar: "تحقّق من شرحي" },
    good: { en: "You covered", ar: "أحسنت في" },
    missed: { en: "You missed", ar: "فاتك" },
    tryAgain: { en: "Try again", ar: "حاول مرة أخرى" },
    simpler: { en: "Explain more simply", ar: "اشرح بأبسط" },
    quizTitle: { en: "Quick check", ar: "اختبار قصير" },
    correct: { en: "Correct", ar: "صحيح" },
    notQuite: { en: "Not quite", ar: "ليس تمامًا" },
    doneTitle: { en: "Lesson complete", ar: "اكتمل الدرس" },
    doneSub: { en: "Well done. Here's what's next.", ar: "أحسنت. إليك الخطوة التالية." },
    nextLesson: { en: "Next lesson", ar: "الدرس التالي" },
    toDashboard: { en: "Back to my plan", ar: "العودة إلى خطتي" },
    companion: { en: "AI companion", ar: "الرفيق الذكي" },
    companionSub: { en: "Ask about this lesson", ar: "اسأل عن هذا الدرس" },
    companionPlaceholder: { en: "What would you like to understand better?", ar: "ما الذي تودّ فهمه أكثر؟" },
    notes: { en: "My notes", ar: "ملاحظاتي" },
    notesPlaceholder: { en: "Write a note…", ar: "اكتب ملاحظة…" },
    progress: { en: "Lesson progress", ar: "تقدّم الدرس" },
    stepCards: { en: "Read the cards", ar: "اقرأ البطاقات" },
    stepExplain: { en: "Explain it back", ar: "اشرحها بكلماتك" },
    stepQuiz: { en: "Answer the quick check", ar: "أجب عن الاختبار" },
    stepDone: { en: "Mark as complete", ar: "أكمل الدرس" },
    voiceUnsupported: {
      en: "Voice input isn't supported in this browser — please type instead.",
      ar: "الإدخال الصوتي غير مدعوم في هذا المتصفح — اكتب بدلًا من ذلك.",
    },
    notFound: { en: "We couldn't find that lesson.", ar: "لم نجد هذا الدرس." },
  },

  ask: {
    title: { en: "Ask & Check", ar: "اسأل وتحقّق" },
    sub: { en: "Get answers you can trust. Always grounded in approved sources.", ar: "إجابات تثق بها، مستندة دائمًا إلى مصادر معتمدة." },
    placeholder: { en: "Ask a question…", ar: "اكتب سؤالك…" },
    send: { en: "Send", ar: "أرسل" },
    newChat: { en: "New chat", ar: "محادثة جديدة" },
    examples: { en: "Example questions", ar: "أسئلة مقترحة" },
    trusted: { en: "Approved sources", ar: "المصادر المعتمدة" },
    related: { en: "Sources in this answer", ar: "مصادر هذه الإجابة" },
    thinking: { en: "Checking the sources…", ar: "نراجع المصادر…" },
    disclaimer: {
      en: "AI-generated. It answers only from approved sources and can still make mistakes — for personal rulings, ask a qualified scholar.",
      ar: "إجابة مولَّدة بالذكاء الاصطناعي. تستند إلى المصادر المعتمدة فقط وقد تخطئ — وللأحكام الشخصية اسأل عالمًا مؤهّلًا.",
    },
    error: {
      en: "The tutor is unavailable right now. Please try again in a moment.",
      ar: "المعلّم غير متاح الآن. حاول مجددًا بعد قليل.",
    },
    tier: {
      A: { en: "Settled, cited", ar: "ثابت وموثّق" },
      B: { en: "Explained from sources", ar: "شرح من المصادر" },
      C: { en: "Scholars differ", ar: "مسألة خلافية" },
      D: { en: "Personal case — referred", ar: "حالة شخصية — إحالة" },
      OUT: { en: "Outside scope", ar: "خارج النطاق" },
      NONE: { en: "No approved source found", ar: "لا يوجد مصدر معتمد" },
    },
    referralTitle: { en: "Speak to a qualified scholar", ar: "استشر عالمًا مؤهّلًا" },
    followUps: { en: "You could also ask", ar: "يمكنك أن تسأل أيضًا" },
  },

  instructor: {
    status: {
      draft: { en: "Draft", ar: "مسودة" },
      in_review: { en: "In review", ar: "قيد المراجعة" },
      published: { en: "Published", ar: "منشور" },
    },
    drafts: { en: "Drafts and lesson reviews", ar: "المسودات ومراجعة الدروس" },
    reviewNote: { en: "Review note", ar: "ملاحظة المراجعة" },
    edit: { en: "Edit", ar: "تحرير" },
    submitted: { en: "Submitted for review.", ar: "أُرسل للمراجعة." },
    submit: { en: "Submit for review", ar: "إرسال للمراجعة" },
    published: { en: "Lesson published.", ar: "نُشر الدرس." },
    publish: { en: "Approve and publish", ar: "اعتماد ونشر" },
    changesRequested: { en: "Changes requested.", ar: "طُلبت تعديلات." },
    requestChanges: { en: "Request changes", ar: "طلب تعديلات" },
    noDrafts: { en: "No drafts yet. Use a sample below and give the new lesson a unique id.", ar: "لا توجد مسودات. استخدم النموذج أدناه وحدّد معرّفًا جديدًا للدرس." },
    draftSaved: { en: "Draft saved. Submit it from the draft list above.", ar: "حُفظت المسودة. أرسلها من القائمة أعلاه." },
    saveDraft: { en: "Save draft", ar: "حفظ المسودة" },
    unavailable: { en: "Course editing will be available soon. You can browse published lessons in the library.", ar: "سيُتاح تحرير الدورات قريبًا. يمكنك تصفّح الدروس المنشورة في المكتبة." },
    sourceApproved: { en: "Source approved.", ar: "اعتُمد المصدر." },
    approveSource: { en: "Approve verified source", ar: "اعتماد المصدر بعد التحقق" },
    lessons: { en: "Lessons", ar: "الدروس" },
    sources: { en: "Sources", ar: "المصادر" },
    backToApp: { en: "Back to app", ar: "العودة إلى التطبيق" },
    navigation: { en: "Studio navigation", ar: "التنقل في الاستوديو" },
    pending: { en: "Pending", ar: "بانتظار المراجعة" },
    sample: { en: "Sample", ar: "نموذج" },
    readyForReview: { en: "Ready for scholarly review", ar: "جاهز للمراجعة العلمية" },
    needsChanges: { en: "Needs changes before review", ar: "يحتاج إلى تعديلات قبل المراجعة" },
    title: { en: "Studio", ar: "الاستوديو" },
    sub: {
      en: "Every lesson and source is approved by a person before learners see it.",
      ar: "يعتمد إنسانٌ كل درس ومصدر قبل أن يصل إلى المتعلّمين.",
    },
    queue: { en: "Review queue", ar: "قائمة المراجعة" },
    sourcesPending: { en: "Sources awaiting review", ar: "مصادر بانتظار المراجعة" },
    lessonsPublished: { en: "Published lessons", ar: "دروس منشورة" },
    aiCheck: { en: "AI pre-check", ar: "فحص أوّلي بالذكاء الاصطناعي" },
    aiCheckSub: {
      en: "Paste a lesson draft (JSON). We verify every citation exists and flag scripture that isn't from a stored source.",
      ar: "الصق مسودة درس (JSON). نتحقّق من وجود كل مصدر، وننبّه على أي نص يشبه النص الشرعي وليس من مصدر مخزّن.",
    },
    run: { en: "Run pre-check", ar: "شغّل الفحص" },
    approve: { en: "Approve", ar: "اعتمد" },
    changes: { en: "Request changes", ar: "اطلب تعديلات" },
    restricted: {
      en: "This workspace is for teachers and admins. Sign in with an approved staff account.",
      ar: "هذه المساحة للمعلّمين والمشرفين. سجّل الدخول بحساب فريق معتمد.",
    },
  },

  quran: {
    tafsir: { en: "Explanation", ar: "التفسير" },
    noTafsir: { en: "The Al-Mukhtasar explanation is not available in", ar: "تفسير المختصر غير متاح باللغة" },
    noVerseTafsir: { en: "The published snapshot has no explanation for this verse.", ar: "لا تحتوي النسخة المنشورة على تفسير لهذه الآية." },
    coversVerses: { en: "This passage covers verses", ar: "يشمل هذا المقطع الآيات" },
    dumpVersion: { en: "dump/catalogue version", ar: "نسخة البيانات / الفهرس" },
    tafsirError: { en: "The explanation could not be loaded. Check your connection and try again.", ar: "تعذّر تحميل التفسير. تحقّق من اتصالك ثم أعد المحاولة." },
    sub: { en: "Read the Quran with a translation of its meanings, verse by verse.", ar: "اقرأ القرآن مع ترجمة معانيه آيةً آية." },
    translation: { en: "Translation", ar: "الترجمة" },
    search: { en: "Search the selected text, or type 2:255", ar: "ابحث في النص المختار، أو اكتب 2:255" },
    searchScope: { en: "Search in", ar: "البحث في" },
    searchFr: { en: "Search the translation, or type 2:255", ar: "ابحث في الترجمة، أو اكتب 2:255" },
    clear: { en: "Clear search", ar: "مسح البحث" },
    found: { en: "verses found", ar: "آية مطابقة" },
    foundOne: { en: "verse found", ar: "آية مطابقة" },
    none: { en: "No verse found. Try fewer or different words.", ar: "لا توجد آية مطابقة. جرّب كلمات أقل أو مختلفة." },
    tooShort: { en: "Type at least two letters.", ar: "اكتب حرفين على الأقل." },
    surah: { en: "Surah", ar: "سورة" },
    findSurah: { en: "Find a surah by name or number", ar: "ابحث عن سورة بالاسم أو الرقم" },
    noSurah: { en: "No surah matches.", ar: "لا توجد سورة مطابقة." },
    verse: { en: "Verse", ar: "الآية" },
    verses: { en: "verses", ar: "آية" },
    page: { en: "Page", ar: "الصفحة" },
    pages: { en: "Pages", ar: "الصفحات" },
    juz: { en: "Juz", ar: "الجزء" },
    display: { en: "Text shown", ar: "النص المعروض" },
    both: { en: "Both", ar: "معًا" },
    prev: { en: "Previous surah", ar: "السورة السابقة" },
    next: { en: "Next surah", ar: "السورة التالية" },
    arabicText: { en: "Arabic text:", ar: "النص العربي:" },
    attribution: { en: "Translation of the meanings:", ar: "ترجمة المعاني:" },
    version: { en: "catalogue version", ar: "نسخة الفهرس" },
    openSource: { en: "Open this surah at the source", ar: "افتح السورة في المصدر" },
    error: { en: "The Quran text could not be loaded. Check your connection and try again.", ar: "تعذّر تحميل نص القرآن. تحقّق من اتصالك ثم أعد المحاولة." },
    retry: { en: "Try again", ar: "أعد المحاولة" },
    listen: { en: "Listen to the surah", ar: "استمع إلى السورة" },
    pause: { en: "Pause the recitation", ar: "أوقف التلاوة مؤقتًا" },
    playVerse: { en: "Listen to verse", ar: "استمع إلى الآية" },
    recitation: { en: "Recitation:", ar: "التلاوة:" },
    hafs: { en: "Hafs from Asim", ar: "حفص عن عاصم" },
    noAudio: { en: "Recitation is not available for this surah.", ar: "التلاوة غير متاحة لهذه السورة." },
    audioError: { en: "The recitation could not be played. Check your connection and try again.", ar: "تعذّر تشغيل التلاوة. تحقّق من اتصالك ثم أعد المحاولة." },
  },

  compare: {
    intro: {
      en: "Explore other beliefs and see how each one compares with Islam. Choose a belief, then a topic.",
      ar: "استكشف المعتقدات الأخرى وتعرّف على مقارنة كلٍّ منها بالإسلام. اختر معتقدًا ثم موضوعًا.",
    },
    reference: { en: "Reference", ar: "المرجع" },
    referenceNote: { en: "Islam is the reference for every comparison.", ar: "الإسلام هو المرجع في كل مقارنة." },
    comparedWith: { en: "Compared with Islam", ar: "مقارنةً بالإسلام" },
    topics: { en: "Comparison topics", ar: "موضوعات المقارنة" },
    traditions: { en: "Traditions", ar: "المذاهب والطوائف" },
    pickTopic: { en: "Choose a topic to open its comparison.", ar: "اختر موضوعًا لفتح مقارنته." },
    breadcrumb: { en: "Breadcrumb", ar: "مسار التنقل" },
    overview: { en: "Overview", ar: "نظرة عامة" },
    back: { en: "Back", ar: "رجوع" },
    islamic: { en: "Islamic perspective", ar: "المنظور الإسلامي" },
    placeholder: { en: "Content will be added after review.", ar: "سيُضاف المحتوى بعد المراجعة." },
    status: {
      draft: { en: "In preparation", ar: "قيد الإعداد" },
      in_review: { en: "In review", ar: "قيد المراجعة" },
      published: { en: "Reviewed", ar: "تمت المراجعة" },
    },
    sections: {
      overview: { en: "Short overview", ar: "نبذة مختصرة" },
      beliefs: { en: "Main beliefs", ar: "المعتقدات الأساسية" },
      common: { en: "Common ground", ar: "القواسم المشتركة" },
      differences: { en: "Key differences", ar: "أبرز الفروق" },
      faq: { en: "Frequently asked questions", ar: "الأسئلة الشائعة" },
      sources: { en: "Sources and references", ar: "المصادر والمراجع" },
    },
  },

  users: {
    title: { en: "Users", ar: "المستخدمون" },
    sub: { en: "Staff sign up as learners. Search for their account and assign a role.", ar: "يسجّل أعضاء الفريق كمتعلّمين. ابحث عن حساباتهم ثم حدّد أدوارهم." },
    restricted: { en: "User management requires a super admin account.", ar: "تتطلّب إدارة المستخدمين حساب مشرف عام." },
    searchLabel: { en: "Email or name", ar: "البريد الإلكتروني أو الاسم" },
    search: { en: "Search", ar: "بحث" },
    results: { en: "Users (up to 50)", ar: "المستخدمون (حتى ٥٠)" },
    empty: { en: "No users found.", ar: "لم يُعثر على مستخدمين." },
    role: { en: "Role", ar: "الدور" },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Role saved.", ar: "حُفظ الدور." },
    self: { en: "You cannot change your own role.", ar: "لا يمكنك تغيير دورك." },
    unavailable: { en: "User management is currently unavailable. Please try again later.", ar: "إدارة المستخدمين غير متاحة حاليًا. يُرجى المحاولة لاحقًا." },
    roles: {
      learner: { en: "Learner", ar: "متعلّم" },
      teacher: { en: "Teacher", ar: "معلّم" },
      admin: { en: "Admin", ar: "مشرف" },
      super_admin: { en: "Super admin", ar: "مشرف عام" },
    },
  },

  common: {
    loading: { en: "Loading…", ar: "جارٍ التحميل…" },
    aiLabel: { en: "AI", ar: "ذكاء اصطناعي" },
    close: { en: "Close", ar: "إغلاق" },
    lang: { en: "العربية", ar: "English" },
  },
} satisfies Record<string, unknown>;

export type Strings = typeof S;
export type { Bi };
