"""Storage contract implemented by memory and PostgreSQL repositories."""

from typing import Protocol

from app.domain.search import Hit


class Repository(Protocol):
    kind: str

    async def list_tracks(self) -> list[dict]: ...
    async def get_lesson(self, lesson_id: str, *, include_unpublished: bool = False) -> dict | None: ...
    async def get_sources(self, ids: list[str]) -> dict[str, dict]: ...
    async def search(self, query: str, *, k: int, embedding: list[float] | None = None) -> list[Hit]: ...
    async def add_review_event(self, lesson_id: str, actor_id: str | None, kind: str, payload: dict) -> None: ...
    async def log_tutor(self, tier: str, citation_ids: list[str], latency_ms: int, track: str | None) -> None: ...
    async def get_role(self, user_id: str) -> str | None: ...
    async def get_account(self, user_id: str) -> dict | None: ...
    async def search_users(self, query: str) -> list[dict]: ...
    async def set_user_role(self, user_id: str, role: str, actor_id: str) -> None: ...
    async def content_bundle(self) -> dict: ...
    async def staff_lessons(self, user_id: str | None, reviewer: bool) -> list[dict]: ...
    async def save_draft(self, draft: dict, actor_id: str | None, reviewer: bool) -> None: ...
    async def lesson_history(self, lesson_id: str) -> list[dict]: ...
    async def archive_lesson(self, lesson_id: str, actor_id: str | None, reviewer: bool) -> None: ...
    async def transition_lesson(
        self,
        lesson_id: str,
        actor_id: str | None,
        kind: str,
        note: str = "",
        *,
        reviewer: bool = False,
        expected: dict | None = None,
    ) -> str: ...
    async def unpublish_lesson(self, lesson_id: str, actor_id: str | None, reviewer: bool) -> None: ...
    async def delete_lesson(self, lesson_id: str, actor_id: str | None, reviewer: bool) -> None: ...
    async def change_planned(
        self, track: str, module: str, actor_id: str | None, *, title: dict | None = None, index: int | None = None
    ) -> None: ...
    async def pending_sources(self) -> list[dict]: ...
    async def add_source(self, source: dict) -> dict: ...
    async def approve_source(self, source_id: str, actor_id: str | None) -> None: ...
    async def ping(self) -> bool: ...
    async def close(self) -> None: ...
